---

- name: TEST Create release dir
  file: path=/opt/app/testing/{{ item.key }} state=directory mode=0755 owner={{ app_user }} group={{ app_group }}
  with_dict: "{{ upstream }}"
  tags: ['debug']

- name: TEST Copy app bin file
  copy: src={{ item.key }} dest=/opt/app/testing/{{ item.key }}/{{ item.key }} owner={{ app_user }} group={{ app_group }} force=yes mode=a+x
  with_dict: "{{ upstream }}"
  tags: ['debug']

- name: TEST Create symlink to new app
  file: src=/opt/app/testing/{{ item.key }}/{{ item.key }} dest=/usr/local/bin/{{ item.key }}-{{ item.value.test_port }} state=link force=yes
  with_dict: "{{ upstream }}"
  tags: ['debug']

- name: TEST Generate systemd config
  template: src=testing.service dest=/etc/systemd/system/{{ item.key }}-{{ item.value.test_port }}.service mode=0644 owner=root group=root
  with_dict: "{{ upstream }}"
  tags: ['debug']

- name: TEST Start "{{ item.key }}-{{ item.value.test_port }}"
  systemd: state=started daemon_reload=yes name={{ item.key }}-{{ item.value.test_port }}.service
  with_dict: "{{ upstream }}"
  tags: ['debug']

- name: TEST Check app status
  uri: url="http://127.0.0.1:{{ item.value.test_port }}/stats" return_content=yes method=GET status_code=200 body_format=json
  register: json_test_response
  with_dict: "{{ upstream }}"
  until: "{{ json_test_response.json.status == 'ok' }}"
  tags: ['debug']

- name: TEST stop test app
  systemd: state=stopped daemon_reload=yes name={{ item.key }}-{{ item.value.test_port }}.service
  with_dict: "{{ upstream }}"
  tags: ['debug']

- name: TEST Delete systemd config
  file: state=absent path=/etc/systemd/system/{{ item.key }}-{{ item.value.test_port }}.service
  with_dict: "{{ upstream }}"
  tags: ['debug']

- name: TEST Delete test app
  file: state=absent path=/usr/local/bin/{{ item.key }}-{{ item.value.test_port }}
  with_dict: "{{ upstream }}"
  tags: ['debug']

- name: TEST Delete test dir
  file: state=absent path=/opt/app/testing
  with_dict: "{{ upstream }}"
  tags: ['debug']