upstream:
  app1:
    test_port: 7009
    ports: [8000, 8001, 8002, 8003, 8004]
  app2:
    test_port: 7010
    ports: [9000, 9001, 9002, 9003, 9004]

front:
  app1:
    listen: 80
    server_name: "_"
    custom_server: |
     error_log /var/log/nginx/app1.error.log;
       access_log /var/log/nginx/app1.access.log;  
    locations:
      "/app1":
        upstream: "app1"
        custom_location: |
          proxy_pass_header x-mobile-device-id;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
      "/app2":
        upstream: "app2"
        custom_location: |
          proxy_pass_header x-mobile-device-id;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;